openapi: 3.0.3
info:
  title: Binar News
  description: |-
    Aplikasi ini akan berguna untuk membantu students mendapatkan informasi terbaru tentang kelas yang ada di Binar Academy.
  contact:
    email: alex@mail.com
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
  - url: https://test.binarnews.com/api/v1
  - url: https://binarnews.com/api/v1
tags:
  - name: user
    description: Everything about your Users
  - name: post
    description: Access to Petstore Posts
paths:
  /users:
    post:
      tags:
        - user
      operationId: post-create-new-user
      summary: ini summary
      description: ini description
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "bujang"
                email:
                  type: string
                  example: "bujang@mail.com"
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                    example: "Created"
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: "bujang"
                      email:
                        type: string
                        example: "bujang@mail.com"
        '400':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Bad Request"
                  data:
                    type: object
                    example: null
    get:
      tags:
        - user
      operationId: get-fetch-all-user
      summary: ini summary
      description: ini description
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          required: false
          description: "page of content"
        - in: query
          name: limit
          schema:
            type: integer
          required: false
          description: "limit content per page"
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                    example: "OK"
                  data:
                    type: object
                    properties:
                      pagination:
                        type: object
                        properties:
                          links:
                            type: object
                            properties:
                              next:
                                type: string
                              prev:
                                type: string
                          total_items:
                            type: integer
                      users:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 1
                            name:
                              type: string
                              example: "bujang"
                            email:
                              type: string
                              example: "bujang@mail.com"
  '/users/{userId}':
    get:
      tags:
        - user
      operationId: get-fetch-user-detail
      summary: ini summary
      description: ini description
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
          description: "userId wajib diisi"
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                    example: "OK"
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: "bujang"
                      email:
                        type: string
                        example: "bujang@mail.com"